import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional
import unittest

_REPO_ROOT = Path(__file__).resolve().parents[2]
_BACKEND_DIR = _REPO_ROOT / "backend"
if str(_BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(_BACKEND_DIR))
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from fastapi import HTTPException
from app.services.search_service import SearchService
from rag.generation import (
    LLMProvider,
    validate_context,
    format_evidence_prompt,
    extract_citations,
    GROUNDING_SYSTEM_PROMPT,
)


class MockLLMProvider(LLMProvider):
    """
    Deterministic mock provider for offline testing without calling live OpenAI APIs.
    """

    def __init__(self, answer_template: Optional[str] = None, fail: bool = False):
        self.answer_template = answer_template
        self.fail = fail
        self.call_count = 0
        self.last_prompt = None
        self.last_system_prompt = None

    def generate(self, prompt: str, system_prompt: Optional[str] = None) -> str:
        self.call_count += 1
        self.last_prompt = prompt
        self.last_system_prompt = system_prompt

        if self.fail:
            raise ConnectionError("Simulated LLM API network error")

        if self.answer_template is not None:
            return self.answer_template

        # Grounded answer with predictable citations
        return (
            "The answer is generated by get_answer() in helpers [Source: sample/helpers.py:1-3]. "
            "In addition, hmm() in the core module invokes get_answer [Source: sample/core.py:13-25]."
        )


class TestAskEndpoint(unittest.TestCase):
    def setUp(self):
        self.search_service = SearchService()
        self.repo_url = "https://github.com/kennethreitz/samplemod"

    def test_valid_grounded_question(self):
        """1. Valid grounded question returns answer, parsed citations, and validated evidence."""
        mock_provider = MockLLMProvider()
        res = self.search_service.ask_repository(
            repo_url=self.repo_url,
            question="Where is the answer generated?",
            top_k=5,
            provider=mock_provider,
        )

        # Provider invoked once with evidence
        self.assertEqual(mock_provider.call_count, 1)
        self.assertIn("Question: Where is the answer generated?", mock_provider.last_prompt)
        self.assertIn("Evidence 1", mock_provider.last_prompt)
        self.assertIn("sample/helpers.py", mock_provider.last_prompt)

        # Structured response fields
        self.assertEqual(res["question"], "Where is the answer generated?")
        self.assertIn("get_answer()", res["answer"])
        self.assertIsInstance(res["citations"], list)
        self.assertIn("sample/helpers.py:1-3", res["citations"])
        self.assertIn("sample/core.py:13-25", res["citations"])
        self.assertTrue(len(res["evidence_used"]) > 0)

        # Verify evidence metadata structure
        top_ev = res["evidence_used"][0]
        self.assertIn("file_path", top_ev)
        self.assertIn("symbol_name", top_ev)
        self.assertIn("source_code", top_ev)
        self.assertIn("start_line", top_ev)
        self.assertIn("end_line", top_ev)
        self.assertIn("retrieval_sources", top_ev)

    def test_empty_question(self):
        """2. Empty question raises HTTPException 400."""
        with self.assertRaises(HTTPException) as ctx:
            self.search_service.ask_repository(
                repo_url=self.repo_url,
                question="   ",
                top_k=5,
            )
        self.assertEqual(ctx.exception.status_code, 400)
        self.assertIn("cannot be empty", ctx.exception.detail)

    def test_invalid_repository_url(self):
        """3. Invalid repository URL raises HTTPException 400."""
        with self.assertRaises(HTTPException) as ctx:
            self.search_service.ask_repository(
                repo_url="https://github.com/nonexistent_org/nonexistent_repo_xyz",
                question="What does this do?",
                top_k=5,
            )
        self.assertEqual(ctx.exception.status_code, 400)

    def test_empty_retrieval_insufficient_evidence(self):
        """4. Empty retrieval results return early with insufficient evidence without calling LLM."""
        mock_provider = MockLLMProvider()

        # Temporarily mock search_repository to return empty results
        original_search = self.search_service.search_repository
        try:
            self.search_service.search_repository = lambda repo_url, query, top_k: {
                "repository_url": repo_url,
                "query": query,
                "results": [],
            }

            res = self.search_service.ask_repository(
                repo_url=self.repo_url,
                question="How does unknown_function work?",
                top_k=5,
                provider=mock_provider,
            )

            # LLM provider must NOT be called when evidence is empty
            self.assertEqual(mock_provider.call_count, 0)
            self.assertEqual(res["citations"], [])
            self.assertEqual(res["evidence_used"], [])
            self.assertIn("insufficient", res["answer"].lower())
        finally:
            self.search_service.search_repository = original_search

    def test_missing_api_key(self):
        """5. Missing OPENAI_API_KEY raises server configuration error (HTTPException 500)."""
        old_key = os.environ.pop("OPENAI_API_KEY", None)
        try:
            with self.assertRaises(HTTPException) as ctx:
                self.search_service.ask_repository(
                    repo_url=self.repo_url,
                    question="How does hmm work?",
                    top_k=5,
                    provider=None,  # Forces OpenAIProvider initialization
                )
            self.assertEqual(ctx.exception.status_code, 500)
            self.assertIn("OPENAI_API_KEY", ctx.exception.detail)
        finally:
            if old_key is not None:
                os.environ["OPENAI_API_KEY"] = old_key

    def test_llm_provider_failure(self):
        """6. Provider failure raises controlled HTTPException 502 with no raw stack trace leaked."""
        failing_provider = MockLLMProvider(fail=True)
        with self.assertRaises(HTTPException) as ctx:
            self.search_service.ask_repository(
                repo_url=self.repo_url,
                question="How does hmm work?",
                top_k=5,
                provider=failing_provider,
            )
        self.assertEqual(ctx.exception.status_code, 502)
        self.assertIn("LLM generation failed", ctx.exception.detail)

    def test_context_validation_and_citation_extraction(self):
        """7. Tests context validation rules and citation extraction."""
        # Test validate_context: drops duplicate spans and empty sources
        raw_items = [
            {"file_path": "a.py", "start_line": 1, "end_line": 10, "source_code": "def foo(): pass"},
            {"file_path": "a.py", "start_line": 1, "end_line": 10, "source_code": "def foo(): pass"},  # duplicate
            {"file_path": "b.py", "start_line": 5, "end_line": 15, "source_code": "   "},             # empty code
            {"file_path": "c.py", "start_line": None, "end_line": 10, "source_code": "x = 1"},         # missing line
            {"file_path": "d.py", "start_line": 1, "end_line": 5, "source_code": "def bar(): pass"},
        ]
        validated = validate_context(raw_items)
        self.assertEqual(len(validated), 2)
        self.assertEqual(validated[0]["file_path"], "a.py")
        self.assertEqual(validated[1]["file_path"], "d.py")

        # Test extract_citations: extracts predictable citations only
        sample_answer = (
            "The core is in [Source: sample/core.py:10-20]. "
            "Helper in [Source: sample/helpers.py:1-5]. "
            "Repeated [Source: sample/core.py:10-20]."
        )
        parsed = extract_citations(sample_answer)
        self.assertEqual(parsed, ["sample/core.py:10-20", "sample/helpers.py:1-5"])


if __name__ == "__main__":
    unittest.main()
