import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional
import unittest

_REPO_ROOT = Path(__file__).resolve().parents[2]
_BACKEND_DIR = _REPO_ROOT / "backend"
if str(_BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(_BACKEND_DIR))
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from fastapi import HTTPException
from app.services.search_service import SearchService
from app.services.flow_service import FlowService
from app.config import settings
from rag.generation import (
    LLMProvider,
    GroqProvider,
    OpenAIProvider,
    validate_context,
    format_evidence_prompt,
    extract_citations,
    GROUNDING_SYSTEM_PROMPT,
    VALID_EXPLANATION_MODES,
    build_system_prompt,
    format_conversation_history,
    build_contextual_query,
    generate_followup_suggestions,
)


class MockLLMProvider(LLMProvider):
    """
    Deterministic mock provider for offline testing without calling live OpenAI APIs.
    """

    def __init__(self, answer_template: Optional[str] = None, fail: bool = False):
        self.answer_template = answer_template
        self.fail = fail
        self.call_count = 0
        self.last_prompt = None
        self.last_system_prompt = None

    def generate(self, prompt: str, system_prompt: Optional[str] = None) -> str:
        self.call_count += 1
        self.last_prompt = prompt
        self.last_system_prompt = system_prompt

        if self.fail:
            raise ConnectionError("Simulated LLM API network error")

        if self.answer_template is not None:
            return self.answer_template

        # Grounded answer with predictable citations
        return (
            "The answer is generated by get_answer() in helpers [Source: sample/helpers.py:1-3]. "
            "In addition, hmm() in the core module invokes get_answer [Source: sample/core.py:13-25]."
        )


class TestAskEndpoint(unittest.TestCase):
    def setUp(self):
        self.search_service = SearchService()
        self.repo_url = "https://github.com/kennethreitz/samplemod"

    def test_valid_grounded_question(self):
        """1. Valid grounded question returns answer, parsed citations, and validated evidence."""
        mock_provider = MockLLMProvider()
        res = self.search_service.ask_repository(
            repo_url=self.repo_url,
            question="Where is the answer generated?",
            top_k=5,
            provider=mock_provider,
        )

        # Provider invoked once with evidence
        self.assertEqual(mock_provider.call_count, 1)
        self.assertIn("Question: Where is the answer generated?", mock_provider.last_prompt)
        self.assertIn("Evidence 1", mock_provider.last_prompt)
        self.assertIn("sample/helpers.py", mock_provider.last_prompt)

        # Structured response fields
        self.assertEqual(res["question"], "Where is the answer generated?")
        self.assertIn("get_answer()", res["answer"])
        self.assertIsInstance(res["citations"], list)
        self.assertIn("sample/helpers.py:1-3", res["citations"])
        self.assertIn("sample/core.py:13-25", res["citations"])
        self.assertTrue(len(res["evidence_used"]) > 0)

        # Verify evidence metadata structure
        top_ev = res["evidence_used"][0]
        self.assertIn("file_path", top_ev)
        self.assertIn("symbol_name", top_ev)
        self.assertIn("source_code", top_ev)
        self.assertIn("start_line", top_ev)
        self.assertIn("end_line", top_ev)
        self.assertIn("retrieval_sources", top_ev)

    def test_empty_question(self):
        """2. Empty question raises HTTPException 400."""
        with self.assertRaises(HTTPException) as ctx:
            self.search_service.ask_repository(
                repo_url=self.repo_url,
                question="   ",
                top_k=5,
            )
        self.assertEqual(ctx.exception.status_code, 400)
        self.assertIn("cannot be empty", ctx.exception.detail)

    def test_invalid_repository_url(self):
        """3. Invalid repository URL raises HTTPException 400."""
        with self.assertRaises(HTTPException) as ctx:
            self.search_service.ask_repository(
                repo_url="https://github.com/nonexistent_org/nonexistent_repo_xyz",
                question="What does this do?",
                top_k=5,
            )
        self.assertEqual(ctx.exception.status_code, 400)

    def test_empty_retrieval_insufficient_evidence(self):
        """4. Empty retrieval results return early with insufficient evidence without calling LLM."""
        mock_provider = MockLLMProvider()

        # Temporarily mock search_repository to return empty results
        original_search = self.search_service.search_repository
        try:
            self.search_service.search_repository = lambda repo_url, query, top_k: {
                "repository_url": repo_url,
                "query": query,
                "results": [],
            }

            res = self.search_service.ask_repository(
                repo_url=self.repo_url,
                question="How does unknown_function work?",
                top_k=5,
                provider=mock_provider,
            )

            # LLM provider must NOT be called when evidence is empty
            self.assertEqual(mock_provider.call_count, 0)
            self.assertEqual(res["citations"], [])
            self.assertEqual(res["evidence_used"], [])
            self.assertIn("couldn't find enough evidence", res["answer"].lower())
        finally:
            self.search_service.search_repository = original_search

    def test_missing_api_key(self):
        """5. Missing API key raises server configuration error (HTTPException 500)."""
        old_groq = os.environ.pop("GROQ_API_KEY", None)
        old_openai = os.environ.pop("OPENAI_API_KEY", None)
        old_settings_groq = settings.GROQ_API_KEY
        old_settings_openai = settings.OPENAI_API_KEY
        settings.GROQ_API_KEY = None
        settings.OPENAI_API_KEY = None
        try:
            with self.assertRaises(HTTPException) as ctx:
                self.search_service.ask_repository(
                    repo_url=self.repo_url,
                    question="How does hmm work?",
                    top_k=5,
                    provider=None,  # Forces default GroqProvider initialization
                )
            self.assertEqual(ctx.exception.status_code, 500)
            self.assertIn("GROQ_API_KEY", ctx.exception.detail)
        finally:
            settings.GROQ_API_KEY = old_settings_groq
            settings.OPENAI_API_KEY = old_settings_openai
            if old_groq is not None:
                os.environ["GROQ_API_KEY"] = old_groq
            if old_openai is not None:
                os.environ["OPENAI_API_KEY"] = old_openai

    def test_llm_provider_failure(self):
        """6. Provider failure raises controlled HTTPException 502 with no raw stack trace leaked."""
        failing_provider = MockLLMProvider(fail=True)
        with self.assertRaises(HTTPException) as ctx:
            self.search_service.ask_repository(
                repo_url=self.repo_url,
                question="How does hmm work?",
                top_k=5,
                provider=failing_provider,
            )
        self.assertEqual(ctx.exception.status_code, 502)
        self.assertIn("LLM generation failed", ctx.exception.detail)

    def test_context_validation_and_citation_extraction(self):
        """7. Tests context validation rules and citation extraction."""
        # Test validate_context: drops duplicate spans and empty sources
        raw_items = [
            {"file_path": "a.py", "start_line": 1, "end_line": 10, "source_code": "def foo(): pass"},
            {"file_path": "a.py", "start_line": 1, "end_line": 10, "source_code": "def foo(): pass"},  # duplicate
            {"file_path": "b.py", "start_line": 5, "end_line": 15, "source_code": "   "},             # empty code
            {"file_path": "c.py", "start_line": None, "end_line": 10, "source_code": "x = 1"},         # missing line
            {"file_path": "d.py", "start_line": 1, "end_line": 5, "source_code": "def bar(): pass"},
        ]
        validated = validate_context(raw_items)
        self.assertEqual(len(validated), 2)
        self.assertEqual(validated[0]["file_path"], "a.py")
        self.assertEqual(validated[1]["file_path"], "d.py")

        # Test extract_citations: extracts predictable citations only
        sample_answer = (
            "The core is in [Source: sample/core.py:10-20]. "
            "Helper in [Source: sample/helpers.py:1-5]. "
            "Repeated [Source: sample/core.py:10-20]."
        )
        parsed = extract_citations(sample_answer)
        self.assertEqual(parsed, ["sample/core.py:10-20", "sample/helpers.py:1-5"])

    def test_groq_provider_initialization_and_validation(self):
        """8. GroqProvider configures defaults and validates GROQ_API_KEY."""
        old_model = os.environ.pop("GROQ_MODEL", None)
        try:
            provider = GroqProvider(api_key="gsk_test123")
            self.assertEqual(provider.model, "llama-3.3-70b-versatile")
            self.assertEqual(provider.api_key, "gsk_test123")
        finally:
            if old_model is not None:
                os.environ["GROQ_MODEL"] = old_model

        custom_provider = GroqProvider(api_key="gsk_test123", model="llama-3.1-8b-instant")
        self.assertEqual(custom_provider.model, "llama-3.1-8b-instant")

        old_key = os.environ.pop("GROQ_API_KEY", None)
        try:
            unconfigured = GroqProvider()
            with self.assertRaises(ValueError) as ctx:
                unconfigured.generate("test prompt")
            self.assertIn("GROQ_API_KEY", str(ctx.exception))
        finally:
            if old_key is not None:
                os.environ["GROQ_API_KEY"] = old_key

    def test_openai_provider_intact(self):
        """9. OpenAIProvider remains intact as an optional provider."""
        old_model = os.environ.pop("OPENAI_MODEL", None)
        try:
            provider = OpenAIProvider(api_key="sk-test123")
            self.assertEqual(provider.model, "gpt-4o-mini")
            self.assertEqual(provider.api_key, "sk-test123")
        finally:
            if old_model is not None:
                os.environ["OPENAI_MODEL"] = old_model

        custom_provider = OpenAIProvider(api_key="sk-test123", model="gpt-4o")
        self.assertEqual(custom_provider.model, "gpt-4o")

        old_key = os.environ.pop("OPENAI_API_KEY", None)
        try:
            unconfigured = OpenAIProvider()
            with self.assertRaises(ValueError) as ctx:
                unconfigured.generate("test prompt")
            self.assertIn("OPENAI_API_KEY", str(ctx.exception))
        finally:
            if old_key is not None:
                os.environ["OPENAI_API_KEY"] = old_key

    def test_ask_beginner_mode(self):
        """10. Beginner mode sets beginner instructions and returns explanation_mode."""
        mock_provider = MockLLMProvider()
        res = self.search_service.ask_repository(
            repo_url=self.repo_url,
            question="What does the core module do?",
            top_k=5,
            explanation_mode="beginner",
            provider=mock_provider,
        )
        self.assertEqual(res["explanation_mode"], "beginner")
        self.assertIn("EXPLANATION MODE: BEGINNER", mock_provider.last_system_prompt)
        self.assertIn("intuitive real-world analogies", mock_provider.last_system_prompt)
        self.assertIsInstance(res.get("suggested_followups"), list)

    def test_ask_developer_mode(self):
        """11. Developer mode sets technical instructions and returns explanation_mode."""
        mock_provider = MockLLMProvider()
        res = self.search_service.ask_repository(
            repo_url=self.repo_url,
            question="What does the core module do?",
            top_k=5,
            explanation_mode="developer",
            provider=mock_provider,
        )
        self.assertEqual(res["explanation_mode"], "developer")
        self.assertIn("EXPLANATION MODE: DEVELOPER", mock_provider.last_system_prompt)
        self.assertIn("precise technical terminology", mock_provider.last_system_prompt)

    def test_ask_interview_mode(self):
        """12. Interview mode sets candidate interview structure and returns explanation_mode."""
        mock_provider = MockLLMProvider()
        res = self.search_service.ask_repository(
            repo_url=self.repo_url,
            question="What does the core module do?",
            top_k=5,
            explanation_mode="interview",
            provider=mock_provider,
        )
        self.assertEqual(res["explanation_mode"], "interview")
        self.assertIn("EXPLANATION MODE: INTERVIEW", mock_provider.last_system_prompt)
        self.assertIn("What problem this solves", mock_provider.last_system_prompt)

    def test_ask_invalid_mode_raises_400(self):
        """13. Invalid explanation mode raises HTTPException 400."""
        mock_provider = MockLLMProvider()
        with self.assertRaises(HTTPException) as ctx:
            self.search_service.ask_repository(
                repo_url=self.repo_url,
                question="What does this do?",
                top_k=5,
                explanation_mode="wizard",
                provider=mock_provider,
            )
        self.assertEqual(ctx.exception.status_code, 400)
        self.assertIn("Invalid explanation mode", ctx.exception.detail)

    def test_ask_conversation_context_and_strict_separation(self):
        """14. Conversation history is included for context but separated from repository evidence."""
        mock_provider = MockLLMProvider()
        conversation = [
            {"role": "user", "content": "How does get_answer work?"},
            {"role": "assistant", "content": "It returns True from helpers [Source: sample/helpers.py:1-3]."},
        ]
        res = self.search_service.ask_repository(
            repo_url=self.repo_url,
            question="Why does it return that value?",
            top_k=5,
            conversation=conversation,
            provider=mock_provider,
        )
        # Check system prompt includes strict evidence separation rule 6
        self.assertIn("Strict Evidence Separation", mock_provider.last_system_prompt)
        self.assertIn("Conversation history is NOT repository evidence", mock_provider.last_system_prompt)

        # Check prompt includes recent conversation context boundary
        self.assertIn("--- RECENT CONVERSATION CONTEXT (For reference only; NOT repository evidence) ---", mock_provider.last_prompt)
        self.assertIn("User: How does get_answer work?", mock_provider.last_prompt)
        self.assertIn("Question: Why does it return that value?", mock_provider.last_prompt)

    def test_ask_backend_history_limit_defensive_capping(self):
        """15. Backend independently caps conversation history to the latest 6 messages."""
        mock_provider = MockLLMProvider()
        long_conversation = [
            {"role": "user", "content": f"TurnQuestion_{i:02d}"} if i % 2 == 0 else {"role": "assistant", "content": f"TurnAnswer_{i:02d}"}
            for i in range(12)
        ]
        # 12 messages: Q00..A11
        # Bounded latest 6 should be: Q06, A07, Q08, A09, Q10, A11
        res = self.search_service.ask_repository(
            repo_url=self.repo_url,
            question="Latest question?",
            top_k=5,
            conversation=long_conversation,
            provider=mock_provider,
        )
        # Earliest messages should NOT appear in provider's prompt
        self.assertNotIn("TurnQuestion_00", mock_provider.last_prompt)
        self.assertNotIn("TurnAnswer_01", mock_provider.last_prompt)
        self.assertNotIn("TurnQuestion_04", mock_provider.last_prompt)
        # Latest 6 messages should appear
        self.assertIn("TurnQuestion_06", mock_provider.last_prompt)
        self.assertIn("TurnAnswer_11", mock_provider.last_prompt)

    def test_contextual_query_builder(self):
        """16. build_contextual_query deterministically combines recent turn with follow-up query."""
        # Simple question without conversation
        q1 = build_contextual_query("How does core.py work?")
        self.assertEqual(q1, "How does core.py work?")

        # Follow-up question with prior user turn
        conv = [
            {"role": "user", "content": "How does get_answer work?"},
            {"role": "assistant", "content": "It returns True."},
        ]
        q2 = build_contextual_query("Why does it do that?", conv)
        self.assertEqual(q2, "How does get_answer work? Why does it do that?")

        # When question is already identical to last user turn, doesn't duplicate
        q3 = build_contextual_query("How does get_answer work?", conv)
        self.assertEqual(q3, "How does get_answer work?")

    def test_deterministic_followup_suggestions(self):
        """17. generate_followup_suggestions generates 2-3 suggestions without LLM."""
        evidence = [
            {
                "file_path": "sample/core.py",
                "symbol_name": "hmm",
                "symbol_type": "FUNCTION",
            },
            {
                "file_path": "sample/helpers.py",
                "symbol_name": "get_answer",
                "symbol_type": "FUNCTION",
            },
        ]
        suggestions = generate_followup_suggestions("What does hmm do?", evidence)
        self.assertIsInstance(suggestions, list)
        self.assertTrue(2 <= len(suggestions) <= 3)
        # Suggestions should reference discovered symbols or logical next steps
        joined = " ".join(suggestions)
        self.assertTrue("get_answer()" in joined or "hmm()" in joined or "?" in joined)


class TestFlowService(unittest.TestCase):
    def setUp(self):
        self.flow_service = FlowService()
        self.repo_url = "https://github.com/kennethreitz/samplemod"

    def test_trace_flow_valid_root_function(self):
        """18. Tracing valid root function ('hmm') returns root node and called functions."""
        res = self.flow_service.trace_flow(
            repo_url=self.repo_url,
            root_function="hmm",
            max_depth=3,
        )
        self.assertEqual(res["repository_url"], self.repo_url)
        self.assertEqual(res["root_function"], "hmm")

        nodes = res["nodes"]
        self.assertGreaterEqual(len(nodes), 2)
        root_node = nodes[0]
        self.assertEqual(root_node["name"], "hmm")
        self.assertEqual(root_node["file_path"], "sample/core.py")
        self.assertEqual(root_node["start_line"], 9)
        self.assertEqual(root_node["end_line"], 12)

        node_names = [n["name"] for n in nodes]
        self.assertIn("get_answer", node_names)
        self.assertIn("get_hmm", node_names)

        edges = res["edges"]
        self.assertGreaterEqual(len(edges), 2)
        for e in edges:
            self.assertEqual(e["type"], "CALLS")
            self.assertTrue(e["source"].startswith("func:"))
            self.assertTrue(e["target"].startswith("func:"))

    def test_trace_flow_depth_strictly_enforced(self):
        """19. Call depth must be strictly between 1 and 3."""
        # Depth 1: Only root node is returned
        res_depth_1 = self.flow_service.trace_flow(
            repo_url=self.repo_url,
            root_function="hmm",
            max_depth=1,
        )
        self.assertEqual(len(res_depth_1["nodes"]), 1)
        self.assertEqual(res_depth_1["nodes"][0]["name"], "hmm")
        self.assertEqual(len(res_depth_1["edges"]), 0)

        # Depth 0 raises 400
        with self.assertRaises(HTTPException) as ctx_0:
            self.flow_service.trace_flow(
                repo_url=self.repo_url,
                root_function="hmm",
                max_depth=0,
            )
        self.assertEqual(ctx_0.exception.status_code, 400)
        self.assertIn("strictly between 1 and 3", ctx_0.exception.detail)

        # Depth 4 raises 400 (per strict user rule: max_depth must be strictly 1-3 only)
        with self.assertRaises(HTTPException) as ctx_4:
            self.flow_service.trace_flow(
                repo_url=self.repo_url,
                root_function="hmm",
                max_depth=4,
            )
        self.assertEqual(ctx_4.exception.status_code, 400)
        self.assertIn("strictly between 1 and 3", ctx_4.exception.detail)

    def test_trace_flow_no_internal_calls(self):
        """20. Function with no calls returns only itself and 0 edges."""
        res = self.flow_service.trace_flow(
            repo_url=self.repo_url,
            root_function="get_answer",
            max_depth=3,
        )
        self.assertEqual(len(res["nodes"]), 1)
        self.assertEqual(res["nodes"][0]["name"], "get_answer")
        self.assertEqual(res["nodes"][0]["file_path"], "sample/helpers.py")
        self.assertEqual(len(res["edges"]), 0)

    def test_trace_flow_unknown_function_raises_404(self):
        """21. Unknown function raises HTTPException 404."""
        with self.assertRaises(HTTPException) as ctx:
            self.flow_service.trace_flow(
                repo_url=self.repo_url,
                root_function="non_existent_function_xyz",
                max_depth=3,
            )
        self.assertEqual(ctx.exception.status_code, 404)
        self.assertIn("couldn't find function", ctx.exception.detail)

    def test_trace_flow_empty_inputs_raise_400(self):
        """22. Empty URL or root function raises HTTPException 400."""
        with self.assertRaises(HTTPException) as ctx1:
            self.flow_service.trace_flow(
                repo_url="",
                root_function="hmm",
            )
        self.assertEqual(ctx1.exception.status_code, 400)

        with self.assertRaises(HTTPException) as ctx2:
            self.flow_service.trace_flow(
                repo_url=self.repo_url,
                root_function="   ",
            )
        self.assertEqual(ctx2.exception.status_code, 400)

    def test_trace_flow_invalid_repository_raises_400(self):
        """23. Invalid repository URL raises HTTPException 400."""
        with self.assertRaises(HTTPException) as ctx:
            self.flow_service.trace_flow(
                repo_url="https://github.com/nonexistent_org/nonexistent_repo_xyz",
                root_function="hmm",
            )
        self.assertEqual(ctx.exception.status_code, 400)

    def test_trace_flow_cycle_and_duplicate_prevention(self):
        """24. Circular call graph does not loop infinitely and avoids duplicate nodes/edges."""
        original_build = self.flow_service.analysis_service.build_architecture_graph
        try:
            self.flow_service.analysis_service.build_architecture_graph = lambda repo_url: {
                "nodes": [
                    {"id": "func:app.py:fn_a", "name": "fn_a", "type": "function", "file_path": "app.py", "start_line": 1, "end_line": 5},
                    {"id": "func:app.py:fn_b", "name": "fn_b", "type": "function", "file_path": "app.py", "start_line": 10, "end_line": 15},
                    {"id": "func:app.py:fn_c", "name": "fn_c", "type": "function", "file_path": "app.py", "start_line": 20, "end_line": 25},
                    {"id": "func:app.py:fn_d", "name": "fn_d", "type": "function", "file_path": "app.py", "start_line": 30, "end_line": 35},
                ],
                "edges": [
                    {"type": "calls", "source": "func:app.py:fn_a", "target": "func:app.py:fn_b"},
                    {"type": "calls", "source": "func:app.py:fn_b", "target": "func:app.py:fn_c"},
                    {"type": "calls", "source": "func:app.py:fn_c", "target": "func:app.py:fn_a"},  # cycle
                    {"type": "calls", "source": "func:app.py:fn_a", "target": "func:app.py:fn_b"},  # duplicate edge
                ],
            }

            res = self.flow_service.trace_flow(
                repo_url=self.repo_url,
                root_function="fn_a",
                max_depth=3,
            )

            node_ids = [n["id"] for n in res["nodes"]]
            self.assertEqual(len(node_ids), len(set(node_ids)))
            self.assertIn("func:app.py:fn_a", node_ids)
            self.assertIn("func:app.py:fn_b", node_ids)
            self.assertIn("func:app.py:fn_c", node_ids)
            self.assertNotIn("func:app.py:fn_d", node_ids)

            edge_keys = [(e["source"], e["target"]) for e in res["edges"]]
            self.assertEqual(len(edge_keys), len(set(edge_keys)))
        finally:
            self.flow_service.analysis_service.build_architecture_graph = original_build

    def test_list_repository_functions(self):
        """25. list_repository_functions returns sorted function list."""
        funcs = self.flow_service.list_repository_functions(repo_url=self.repo_url)
        self.assertIsInstance(funcs, list)
        self.assertGreater(len(funcs), 0)
        func_names = [f["name"] for f in funcs]
        self.assertIn("hmm", func_names)
        self.assertIn("get_answer", func_names)
        self.assertIn("get_hmm", func_names)

    def test_project_overview_grounded_fields(self):
        """26. get_project_overview returns strictly grounded description, purpose, and problem solved."""
        from app.services.analysis_service import AnalysisService
        service = AnalysisService()
        overview = service.get_project_overview(repo_url=self.repo_url)

        self.assertIn("repository_name", overview)
        self.assertIn("samplemod", overview["repository_name"])
        self.assertIn("description", overview)
        self.assertTrue(len(overview["description"]) > 10)
        self.assertIn("problem_solved", overview)
        self.assertIn("core_purpose", overview)
        self.assertIsInstance(overview["key_features"], list)
        self.assertGreater(len(overview["key_features"]), 0)
        self.assertIsInstance(overview["use_cases"], list)
        self.assertGreater(len(overview["use_cases"]), 0)

    def test_project_overview_tech_stack_evidence(self):
        """27. Tech stack items are marked directly_detected with verified sources."""
        from app.services.analysis_service import AnalysisService
        service = AnalysisService()
        overview = service.get_project_overview(repo_url=self.repo_url)

        tech_stack = overview.get("tech_stack", [])
        self.assertGreater(len(tech_stack), 0)

        for item in tech_stack:
            self.assertEqual(item["detection_type"], "directly_detected")
            self.assertTrue(len(item["source"]) > 0)
            self.assertIn(item["category"], [
                "Language", "Backend / Framework", "Testing", "Packaging / Build", "Infrastructure / Tooling"
            ])

        tech_names = [t["name"] for t in tech_stack]
        self.assertTrue(any("Python" in name for name in tech_names))
        self.assertTrue(any("unittest" in name or "nose" in name for name in tech_names))

    def test_project_overview_conceptual_architecture(self):
        """28. Conceptual architecture provides 3 functional layers."""
        from app.services.analysis_service import AnalysisService
        service = AnalysisService()
        overview = service.get_project_overview(repo_url=self.repo_url)

        layers = overview.get("conceptual_architecture", [])
        self.assertGreaterEqual(len(layers), 2)
        layer_ids = [l["id"] for l in layers]
        self.assertIn("layer-1", layer_ids)
        self.assertIn("layer-2", layer_ids)

        for layer in layers:
            self.assertTrue(len(layer["name"]) > 0)
            self.assertTrue(len(layer["role"]) > 0)
            self.assertTrue(len(layer["description"]) > 0)
            self.assertIsInstance(layer["files"], list)

    def test_project_overview_workflows_trace_flow(self):
        """29. Key workflows identify root functions and step-by-step descriptions."""
        from app.services.analysis_service import AnalysisService
        service = AnalysisService()
        overview = service.get_project_overview(repo_url=self.repo_url)

        workflows = overview.get("workflows", [])
        self.assertGreater(len(workflows), 0)

        root_functions = [w["root_function"] for w in workflows]
        self.assertIn("hmm", root_functions)

        hmm_wf = next(w for w in workflows if w["root_function"] == "hmm")
        self.assertTrue(len(hmm_wf["steps"]) >= 2)
        self.assertTrue(any("get_answer" in step or "helpers" in step for step in hmm_wf["steps"]))

    def test_project_overview_snapshot_facts(self):
        """30. Snapshot facts accurately reflect file counts and modules."""
        from app.services.analysis_service import AnalysisService
        service = AnalysisService()
        overview = service.get_project_overview(repo_url=self.repo_url)

        snapshot = overview.get("snapshot", {})
        self.assertEqual(snapshot.get("primary_language"), "Python")
        self.assertGreaterEqual(snapshot.get("total_files", 0), 10)
        self.assertGreaterEqual(snapshot.get("major_modules_count", 0), 1)
        self.assertIn("sample", snapshot.get("major_modules", []))

    def test_architecture_graph_includes_project_overview(self):
        """31. build_architecture_graph returns project_overview seamlessly."""
        from app.services.analysis_service import AnalysisService
        service = AnalysisService()
        graph = service.build_architecture_graph(repo_url=self.repo_url)

        self.assertIn("project_overview", graph)
        self.assertIsNotNone(graph["project_overview"])
        self.assertEqual(graph["project_overview"]["repository_name"], "kennethreitz/samplemod")


if __name__ == "__main__":
    unittest.main()


